/**
 * Typed wrapper around the Rust core native addon (`@thupham/volley-core`).
 *
 * The addon is CommonJS (generated by napi-rs), so we load it via `createRequire`
 * from this ES module. The FFI contract is JSON string in / JSON string out; we parse
 * results here so the rest of the server works with plain objects.
 */
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

interface NativeCore {
  version(): string;
  httpRequest(requestJson: string): Promise<string>;
  graphqlRequest(requestJson: string): Promise<string>;
  graphqlIntrospect(requestJson: string): Promise<string>;
  wsSession(requestJson: string): Promise<string>;
  wsOpen(requestJson: string): Promise<string>;
  wsSend(handle: string, messageJson: string): string;
  wsRecv(requestJson: string): Promise<string>;
  wsClose(handle: string): string;
  sseSession(requestJson: string): Promise<string>;
  jsonQuery(documentJson: string, path: string): string;
}

const native = require("@thupham/volley-core") as NativeCore;

export function coreVersion(): string {
  return native.version();
}

/** Standard result document returned by the execution functions. */
export interface ExecResult {
  ok: boolean;
  error: string | null;
  status?: number | null;
  statusText?: string;
  timeMs?: number;
  headers?: Record<string, string>;
  bodyJson?: unknown;
  bodyText?: string | null;
  bodyBytes?: number;
  bodyShape?: unknown;
  bodyPreview?: unknown;
  assertions?: AssertionReport;
  extracted?: Record<string, unknown>;
  graphqlErrors?: unknown;
  // streaming
  connected?: boolean;
  frameCount?: number;
  frames?: unknown[];
  framesPreview?: unknown;
  eventCount?: number;
  events?: unknown[];
  eventsPreview?: unknown;
  note?: string | null;
  // introspection / persistent ws
  schema?: unknown;
  handle?: string;
  count?: number;
  remaining?: number;
  closed?: boolean;
}

export interface AssertionReport {
  passed: number;
  failed: number;
  skipped: number;
  results: { ok: boolean; skipped?: boolean; desc: string; detail?: string }[];
}

export async function httpRequest(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.httpRequest(JSON.stringify(spec))) as ExecResult;
}
export async function graphqlRequest(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.graphqlRequest(JSON.stringify(spec))) as ExecResult;
}
export async function graphqlIntrospect(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.graphqlIntrospect(JSON.stringify(spec))) as ExecResult;
}
export async function wsSession(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.wsSession(JSON.stringify(spec))) as ExecResult;
}
export async function wsOpen(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.wsOpen(JSON.stringify(spec))) as ExecResult;
}
export function wsSend(handle: string, message: unknown): ExecResult {
  return JSON.parse(native.wsSend(handle, JSON.stringify(message))) as ExecResult;
}
export async function wsRecv(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.wsRecv(JSON.stringify(spec))) as ExecResult;
}
export function wsClose(handle: string): ExecResult {
  return JSON.parse(native.wsClose(handle)) as ExecResult;
}
export async function sseSession(spec: unknown): Promise<ExecResult> {
  return JSON.parse(await native.sseSession(JSON.stringify(spec))) as ExecResult;
}
export function jsonQuery(document: unknown, path: string): { found: boolean; value: unknown; error?: string } {
  return JSON.parse(native.jsonQuery(JSON.stringify(document), path));
}
