packages:
  - "crates/*"
  - "packages/*"
  - "apps/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@thupham/volley-core-darwin-arm64@1.0.4 || 1.0.5 || 1.0.6'
