/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Introspect a GraphQL endpoint and return a summarized schema (root fields + type names). */
export declare function graphqlIntrospect(requestJson: string): Promise<string>

/** Execute a GraphQL query/mutation over HTTP. */
export declare function graphqlRequest(requestJson: string): Promise<string>

/** Execute a REST/HTTP request. Input/output are JSON strings (see `docs/mcp-tools.md`). */
export declare function httpRequest(requestJson: string): Promise<string>

/**
 * Run a JSONPath (RFC 9535) selector against a JSON document. Used by
 * `inspect_response` to let the agent pull only the slice it needs from a stored body.
 * Supports filters: `$.items[?@.id==1]`, slices: `$.items[0:5]`, wildcards: `$..field`.
 * String literals in filters must use double quotes: `[?@.name=="x"]`.
 */
export declare function jsonQuery(documentJson: string, path: string): string

/** Subscribe to an SSE endpoint and collect events until a stop condition. */
export declare function sseSession(requestJson: string): Promise<string>

/** Returns the core engine version (compiled from Cargo.toml). */
export declare function version(): string

/** Close a persistent WebSocket connection. */
export declare function wsClose(handle: string): string

/** Open a persistent WebSocket connection; returns a handle for ws_send/ws_recv/ws_close. */
export declare function wsOpen(requestJson: string): Promise<string>

/** Receive buffered frames from a persistent WebSocket connection (with an optional wait). */
export declare function wsRecv(requestJson: string): Promise<string>

/** Send a message ({json} or {text}) on a persistent WebSocket connection. */
export declare function wsSend(handle: string, messageJson: string): string

/** Open a bounded WebSocket session: connect, send, collect frames, return a summary. */
export declare function wsSession(requestJson: string): Promise<string>
